// <auto-generated />
using System;
using DualNewsSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DualNewsSearch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    [Migration("20260811015200_InitialDmCreate")]
    partial class InitialDmCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("DualNewsSearch.Infrastructure.Persistence.DesiredDocumentEntity", b =>
                {
                    b.Property<string>("NewsId")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("news_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("content_html");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("content_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("DesiredOperation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<long?>("EsAppliedVersion")
                        .HasColumnType("BIGINT");

                    b.Property<string>("EsLastError")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime?>("EsNextRetryAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("EsRetryCount")
                        .HasColumnType("INT");

                    b.Property<string>("EsStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<long>("IndexVersion")
                        .HasColumnType("BIGINT")
                        .HasColumnName("index_version");

                    b.Property<DateTime>("PublishTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("VespaAppliedVersion")
                        .HasColumnType("BIGINT");

                    b.Property<string>("VespaLastError")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime?>("VespaNextRetryAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("VespaRetryCount")
                        .HasColumnType("INT");

                    b.Property<string>("VespaStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.HasKey("NewsId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_aura_doc_updated");

                    b.HasIndex("SourceType", "PublishTime")
                        .HasDatabaseName("ix_aura_doc_type_time");

                    b.ToTable("aurasearch_desired_documents", (string)null);
                });

            modelBuilder.Entity("DualNewsSearch.Infrastructure.Persistence.IndexOutboxEntity", b =>
                {
                    b.Property<string>("NewsId")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("news_id");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("ClaimToken")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<DateTime?>("ClaimedUntil")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("NewsId");

                    b.HasIndex("AvailableAt", "ClaimedUntil")
                        .HasDatabaseName("ix_aura_outbox_claim");

                    b.ToTable("aurasearch_index_outbox", (string)null);
                });

            modelBuilder.Entity("DualNewsSearch.Infrastructure.Persistence.SearchClickEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClickPosition")
                        .HasColumnType("INT");

                    b.Property<DateTime>("ClickedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long?>("DwellTimeMs")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("NewsId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<Guid>("SearchTraceId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_aura_click_expiry");

                    b.HasIndex("SearchTraceId", "NewsId")
                        .HasDatabaseName("ix_aura_click_trace_news");

                    b.ToTable("aurasearch_search_clicks", (string)null);
                });

            modelBuilder.Entity("DualNewsSearch.Infrastructure.Persistence.SearchQueryEntity", b =>
                {
                    b.Property<Guid>("SearchTraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("search_trace_id");

                    b.Property<string>("DegradationMode")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<int>("EsHitCount")
                        .HasColumnType("INT");

                    b.Property<long>("EsLatencyMs")
                        .HasColumnType("BIGINT");

                    b.Property<bool>("EsTimeout")
                        .HasColumnType("BIT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<long>("FusionLatencyMs")
                        .HasColumnType("BIGINT");

                    b.Property<int>("MergedUniqueCount")
                        .HasColumnType("INT");

                    b.Property<string>("NormalizedQuery")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("QueryText")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ResultVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("SearchMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<DateTime>("SearchTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<long>("TotalLatencyMs")
                        .HasColumnType("BIGINT");

                    b.Property<int>("VespaHitCount")
                        .HasColumnType("INT");

                    b.Property<long>("VespaLatencyMs")
                        .HasColumnType("BIGINT");

                    b.Property<bool>("VespaTimeout")
                        .HasColumnType("BIT");

                    b.HasKey("SearchTraceId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_aura_query_expiry");

                    b.HasIndex("ResultVersion", "SearchTime")
                        .HasDatabaseName("ix_aura_query_version_time");

                    b.ToTable("aurasearch_search_queries", (string)null);
                });

            modelBuilder.Entity("DualNewsSearch.Infrastructure.Persistence.SearchResultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasAnnotation("Dm:ValueGenerationStrategy", DmValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EsRank")
                        .HasColumnType("INT");

                    b.Property<double?>("EsScore")
                        .HasColumnType("FLOAT");

                    b.Property<bool>("Exposed")
                        .HasColumnType("BIT");

                    b.Property<DateTime?>("ExposedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("NewsId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("PresentInEs")
                        .HasColumnType("BIT");

                    b.Property<bool>("PresentInVespa")
                        .HasColumnType("BIT");

                    b.Property<int?>("RrfRank")
                        .HasColumnType("INT");

                    b.Property<double?>("RrfScore")
                        .HasColumnType("FLOAT");

                    b.Property<Guid>("SearchTraceId")
                        .HasColumnType("CHAR(36)");

                    b.Property<int?>("VespaRank")
                        .HasColumnType("INT");

                    b.Property<double?>("VespaRelevance")
                        .HasColumnType("FLOAT");

                    b.HasKey("Id");

                    b.HasIndex("SearchTraceId", "NewsId")
                        .IsUnique()
                        .HasDatabaseName("ux_aura_result_trace_news");

                    b.HasIndex("SearchTraceId", "RrfRank")
                        .HasDatabaseName("ix_aura_result_trace_rank");

                    b.ToTable("aurasearch_search_results", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
